"""Added invited_by to user table

Revision ID: 2a100d822b22
Revises: a23319fd29c5
Create Date: 2024-08-25 04:48:01.958152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a100d822b22'
down_revision = 'a23319fd29c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['invited_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invited_by')

    # ### end Alembic commands ###
